spring.application.name=incident-res-platform
server.port=8080

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration=3600